// Static practice bank -- Target H: Understand solving equations as a
// process of reasoning and explain the reasoning.
// 5 variations of each allowed item type (multiple_choice, matching_tables,
// equation_numeric) per Evidence Required statement.

export const TARGET_BANK_H = {
  "1": [
    { type: "equation_numeric", stem: "Solve: sqrt{x+1} = 3. Find x.", data: { answerLabel: "x =", correctAnswer: "8" } },
    { type: "equation_numeric", stem: "Solve: sqrt{2x-3} = 5. Find x.", data: { answerLabel: "x =", correctAnswer: "14" } },
    { type: "equation_numeric", stem: "Solve: frac{1}{x} + frac{1}{2} = 1. Find x.", data: { answerLabel: "x =", correctAnswer: "2" } },
    { type: "equation_numeric", stem: "Solve: frac{3}{x-1} = 6. Find x.", data: { answerLabel: "x =", correctAnswer: "frac{3}{2}" } },
    { type: "equation_numeric", stem: "How many real solutions does sqrt{x} = -4 have?", data: { answerLabel: "Number of real solutions =", correctAnswer: "0" } },
    { type: "multiple_choice", stem: "How many real solutions does the equation sqrt{x-3} = 5 have?", data: { options: [{id:"A",text:"Exactly one"},{id:"B",text:"Exactly two"},{id:"C",text:"Infinitely many"},{id:"D",text:"None"}], correctId: "A" } },
    { type: "multiple_choice", stem: "How many real solutions does frac{4}{x} = 0 have?", data: { options: [{id:"A",text:"None"},{id:"B",text:"Exactly one"},{id:"C",text:"Exactly two"},{id:"D",text:"Infinitely many"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve: sqrt{x+6} = 4", data: { options: [{id:"A",text:"x = 10"},{id:"B",text:"x = 2"},{id:"C",text:"x = 16"},{id:"D",text:"x = -2"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve: frac{2}{x+3} = 4", data: { options: [{id:"A",text:"x = -frac{5}{2}"},{id:"B",text:"x = frac{5}{2}"},{id:"C",text:"x = -1"},{id:"D",text:"x = 1"}], correctId: "A" } },
    { type: "multiple_choice", stem: "How many real solutions does sqrt{x} = x have, for real x \u2265 0?", data: { options: [{id:"A",text:"Exactly two (x=0 and x=1)"},{id:"B",text:"Exactly one"},{id:"C",text:"None"},{id:"D",text:"Infinitely many"}], correctId: "A" } },
    { type: "matching_tables", stem: "Match each radical or rational equation to its number of real solutions.", data: { rows: ["sqrt{x-2}=6","sqrt{x}=-3","frac{5}{x}=1"], columns: ["One real solution","No real solutions","One real solution"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to its solution.", data: { rows: ["sqrt{x+1}=3","frac{1}{x}+frac{1}{2}=1","frac{3}{x-1}=6"], columns: ["x=8","x=2","x=frac{3}{2}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to its solution.", data: { rows: ["sqrt{2x-3}=5","sqrt{x+6}=4","frac{2}{x+3}=4"], columns: ["x=14","x=10","x=-frac{5}{2}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to whether it has one, zero, or infinitely many real solutions.", data: { rows: ["sqrt{x-1}=5","sqrt{x}=-2","frac{0}{x}=0 for x\u22600"], columns: ["One solution","Zero solutions","Infinitely many solutions"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to its solution.", data: { rows: ["sqrt{x-3}=5","frac{4}{x}=2","sqrt{x}=6"], columns: ["x=28","x=2","x=36"], correct: [0,1,2] } },
  ],

  "2": [
    { type: "equation_numeric", stem: "Solve sqrt{x} = x-2 by squaring both sides. This gives two algebraic solutions, x=1 and x=4. Which one is extraneous?", data: { answerLabel: "Extraneous solution: x =", correctAnswer: "1" } },
    { type: "equation_numeric", stem: "Solve sqrt{x-2} = x-4 by squaring both sides. This gives x=3 and x=6. Which one is extraneous?", data: { answerLabel: "Extraneous solution: x =", correctAnswer: "3" } },
    { type: "equation_numeric", stem: "Solve sqrt{x+3} = x-3 by squaring both sides. This gives x=1 and x=6. Which one is the valid solution?", data: { answerLabel: "Valid solution: x =", correctAnswer: "6" } },
    { type: "equation_numeric", stem: "For the equation sqrt{x} = x-2, verify x=4 by substitution. What is sqrt{4}?", data: { answerLabel: "sqrt{4} =", correctAnswer: "2" } },
    { type: "equation_numeric", stem: "For the equation sqrt{x-2} = x-4, verify x=3 by substitution. What is sqrt{3-2}?", data: { answerLabel: "sqrt{3-2} =", correctAnswer: "1" } },
    { type: "multiple_choice", stem: "When solving sqrt{x} = x-2, why must every algebraic solution be checked in the original equation?", data: { options: [{id:"A",text:"Squaring both sides can introduce solutions that don't satisfy the original equation"},{id:"B",text:"Square roots always have two solutions"},{id:"C",text:"Checking is optional and never changes the answer"},{id:"D",text:"The equation has no real solutions"}], correctId: "A" } },
    { type: "multiple_choice", stem: "After squaring sqrt{x+3} = x-3, you get x=1 and x=6. Which is extraneous?", data: { options: [{id:"A",text:"x=1, since sqrt{4}=2 does not equal 1-3=-2"},{id:"B",text:"x=6, since it doesn't satisfy the squared equation"},{id:"C",text:"Neither is extraneous"},{id:"D",text:"Both are extraneous"}], correctId: "A" } },
    { type: "multiple_choice", stem: "A student solves a radical equation and gets x=-2 as an algebraic solution, but the original equation has sqrt{x} on one side. What should the student conclude?", data: { options: [{id:"A",text:"x=-2 is extraneous, since sqrt{x} requires x\u22650"},{id:"B",text:"x=-2 is automatically valid"},{id:"C",text:"The equation has no solutions at all"},{id:"D",text:"The equation must be solved again from scratch"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Why can extraneous solutions arise specifically when solving rational equations (with variables in a denominator)?", data: { options: [{id:"A",text:"Multiplying both sides by an expression containing the variable can introduce values that make the original denominator zero"},{id:"B",text:"Rational equations never have real solutions"},{id:"C",text:"Rational equations always have exactly one solution"},{id:"D",text:"Extraneous solutions cannot occur in rational equations"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solving frac{x}{x-2} = frac{2}{x-2} algebraically gives x=2. Why is this extraneous?", data: { options: [{id:"A",text:"x=2 makes the original denominator (x-2) equal to zero"},{id:"B",text:"x=2 is negative"},{id:"C",text:"The equation has no algebraic solutions"},{id:"D",text:"It is not actually extraneous"}], correctId: "A" } },
    { type: "matching_tables", stem: "Match each radical equation to its extraneous solution (the algebraic solution that does not satisfy the original equation).", data: { rows: ["sqrt{x}=x-2 (solutions x=1,4)","sqrt{x-2}=x-4 (solutions x=3,6)","sqrt{x+3}=x-3 (solutions x=1,6)"], columns: ["x=1","x=3","x=1"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each radical equation to its valid (non-extraneous) solution.", data: { rows: ["sqrt{x}=x-2 (solutions x=1,4)","sqrt{x-2}=x-4 (solutions x=3,6)","sqrt{x+3}=x-3 (solutions x=1,6)"], columns: ["x=4","x=6","x=6"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each situation to whether it can produce extraneous solutions.", data: { rows: ["Squaring both sides of a radical equation","Adding the same constant to both sides","Multiplying both sides by an expression with the variable"], columns: ["Can introduce extraneous solutions","Cannot introduce extraneous solutions","Can introduce extraneous solutions"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each algebraic solution to whether it is valid or extraneous, given the original equation sqrt{x-2}=x-4.", data: { rows: ["x=3","x=6"], columns: ["Extraneous","Valid"], correct: [0,1] } },
    { type: "matching_tables", stem: "Match each algebraic solution to whether it is valid or extraneous, given the original equation sqrt{x}=x-2.", data: { rows: ["x=1","x=4"], columns: ["Extraneous","Valid"], correct: [0,1] } },
  ],

  "3": [
    { type: "equation_numeric", stem: "Solve for y: sqrt{x+y} = 5, when x = 9. Find y.", data: { answerLabel: "y =", correctAnswer: "16" } },
    { type: "equation_numeric", stem: "Solve for x: frac{x}{y} = 4, when y = 7. Find x.", data: { answerLabel: "x =", correctAnswer: "28" } },
    { type: "equation_numeric", stem: "Solve for y: frac{6}{x+y} = 2, when x = 1. Find y.", data: { answerLabel: "y =", correctAnswer: "2" } },
    { type: "equation_numeric", stem: "Solve for x: sqrt{xy} = 6, when y = 4. Find x.", data: { answerLabel: "x =", correctAnswer: "9" } },
    { type: "equation_numeric", stem: "Solve for y: frac{x}{2y} = 3, when x = 12. Find y.", data: { answerLabel: "y =", correctAnswer: "2" } },
    { type: "multiple_choice", stem: "To solve sqrt{x+y}=5 for y given a value of x, the first step is to:", data: { options: [{id:"A",text:"Square both sides to eliminate the radical"},{id:"B",text:"Divide both sides by x"},{id:"C",text:"Add x to both sides"},{id:"D",text:"Take the square root of both sides again"}], correctId: "A" } },
    { type: "multiple_choice", stem: "To solve frac{6}{x+y}=2 for y, the first step is to:", data: { options: [{id:"A",text:"Multiply both sides by (x+y)"},{id:"B",text:"Divide both sides by 6"},{id:"C",text:"Square both sides"},{id:"D",text:"Add x to both sides directly"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve for x: sqrt{xy}=6, when y=9.", data: { options: [{id:"A",text:"x = 4"},{id:"B",text:"x = 36"},{id:"C",text:"x = 54"},{id:"D",text:"x = frac{2}{3}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve for y: frac{x}{3y}=2, when x=18.", data: { options: [{id:"A",text:"y = 3"},{id:"B",text:"y = 27"},{id:"C",text:"y = 9"},{id:"D",text:"y = frac{1}{3}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve for x: frac{2x}{y}=8, when y=5.", data: { options: [{id:"A",text:"x = 20"},{id:"B",text:"x = 10"},{id:"C",text:"x = 40"},{id:"D",text:"x = frac{5}{4}"}], correctId: "A" } },
    { type: "matching_tables", stem: "Match each multi-variable equation and given value to the solved variable.", data: { rows: ["sqrt{x+y}=5, x=9, find y","frac{x}{y}=4, y=7, find x","sqrt{xy}=6, y=4, find x"], columns: ["y=16","x=28","x=9"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to the correct first step for solving it for the indicated variable.", data: { rows: ["sqrt{x+y}=5, solve for y","frac{6}{x+y}=2, solve for y","sqrt{xy}=6, solve for x"], columns: ["Square both sides","Multiply both sides by (x+y)","Square both sides"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation and given value to the solved variable.", data: { rows: ["frac{x}{2y}=3, x=12, find y","sqrt{xy}=6, y=9, find x","frac{2x}{y}=8, y=5, find x"], columns: ["y=2","x=4","x=20"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to the variable it is solved for.", data: { rows: ["sqrt{x+y}=5, solving for y given x","frac{x}{y}=4, solving for x given y","frac{x}{3y}=2, solving for y given x"], columns: ["y","x","y"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each multi-variable equation and given value to the solved variable.", data: { rows: ["frac{6}{x+y}=2, x=1, find y","frac{x}{3y}=2, x=18, find y","frac{2x}{y}=8, y=5, find x"], columns: ["y=2","y=3","x=20"], correct: [0,1,2] } },
  ],

  "4": [
    { type: "equation_numeric", stem: "The equation frac{2}{x}=frac{4}{2x} is equivalent to the original for all x\u22600. Simplify frac{4}{2x} to confirm. What is the simplified form?", data: { answerLabel: "Simplified form =", correctAnswer: "frac{2}{x}" } },
    { type: "equation_numeric", stem: "Verify that sqrt{4x}=2sqrt{x} for x\u22650 by evaluating both sides at x=9. What is sqrt{4(9)}?", data: { answerLabel: "sqrt{4(9)} =", correctAnswer: "6" } },
    { type: "equation_numeric", stem: "Verify that sqrt{4x}=2sqrt{x} at x=9 by evaluating the other side. What is 2sqrt{9}?", data: { answerLabel: "2sqrt{9} =", correctAnswer: "6" } },
    { type: "equation_numeric", stem: "The equations frac{x}{x-1}=2 and x=2(x-1) are equivalent for x\u22601. Solve x=2(x-1) for x.", data: { answerLabel: "x =", correctAnswer: "2" } },
    { type: "equation_numeric", stem: "Verify that frac{6}{2x}=frac{3}{x} for x\u22600 by evaluating both sides at x=3. What is frac{6}{2(3)}?", data: { answerLabel: "frac{6}{2(3)} =", correctAnswer: "1" } },
    { type: "multiple_choice", stem: "Which equation is equivalent to sqrt{x}=5, for x\u22650?", data: { options: [{id:"A",text:"x = 25"},{id:"B",text:"x = 10"},{id:"C",text:"x = 2.5"},{id:"D",text:"sqrt{x}=25"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which equation is equivalent to frac{3}{x}=6, for x\u22600?", data: { options: [{id:"A",text:"3 = 6x"},{id:"B",text:"x = 6"},{id:"C",text:"3x = 6"},{id:"D",text:"x = 18"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which expression is equivalent to sqrt{9x} for x\u22650?", data: { options: [{id:"A",text:"3sqrt{x}"},{id:"B",text:"9sqrt{x}"},{id:"C",text:"sqrt{9}+sqrt{x}"},{id:"D",text:"3x"}], correctId: "A" } },
    { type: "multiple_choice", stem: "The equation frac{x+2}{x-1}=3 is equivalent to which of the following, for x\u22601?", data: { options: [{id:"A",text:"x+2 = 3(x-1)"},{id:"B",text:"x+2 = 3x-1"},{id:"C",text:"x = 3(x-1)"},{id:"D",text:"x+2 = 3x"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Two equations are equivalent if they:", data: { options: [{id:"A",text:"Have exactly the same solution set"},{id:"B",text:"Look identical when written out"},{id:"C",text:"Both contain a radical"},{id:"D",text:"Both contain a fraction"}], correctId: "A" } },
    { type: "matching_tables", stem: "Match each equation to an equivalent form.", data: { rows: ["sqrt{x}=5","frac{3}{x}=6","frac{x+2}{x-1}=3"], columns: ["x=25","3=6x","x+2=3(x-1)"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its equivalent simplified form.", data: { rows: ["sqrt{9x}, for x\u22650","sqrt{4x}, for x\u22650","frac{4}{2x}, for x\u22600"], columns: ["3sqrt{x}","2sqrt{x}","frac{2}{x}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each pair of equations to whether they are equivalent.", data: { rows: ["sqrt{x}=5 and x=25","frac{3}{x}=6 and x=18","frac{3}{x}=6 and 3=6x"], columns: ["Equivalent","Not equivalent","Equivalent"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to the equation formed by clearing its fraction or radical.", data: { rows: ["frac{x+2}{x-1}=3, for x\u22601","sqrt{x-1}=4, for x\u22651","frac{5}{x+3}=1, for x\u2260-3"], columns: ["x+2=3(x-1)","x-1=16","5=x+3"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each original equation to its equivalent cleared form.", data: { rows: ["sqrt{2x}=6, for x\u22650","frac{x}{4}=5","frac{x-3}{2}=7"], columns: ["2x=36","x=20","x-3=14"], correct: [0,1,2] } },
  ],
};
