// Static practice bank -- Target A: Extend the properties of exponents to
// rational exponents / Use properties of rational and irrational numbers /
// Reason quantitatively and use units to solve problems.
// 5 variations of each allowed item type (multiple_choice, multi_select,
// matching_tables, equation_numeric) per Evidence Required statement.
// Combined into the full TARGET_BANK object by targetBank.js.

export const TARGET_BANK_A = {
  "1": [
    { type: "equation_numeric", stem: "Rewrite sqrt{x} using a rational exponent x^{a/b}. What is the exponent?", data: { answerLabel: "Exponent =", correctAnswer: "frac{1}{2}" } },
    { type: "equation_numeric", stem: "Rewrite sqrt[3]{x} using a rational exponent x^{a/b}. What is the exponent?", data: { answerLabel: "Exponent =", correctAnswer: "frac{1}{3}" } },
    { type: "equation_numeric", stem: "Rewrite sqrt[4]{x^{3}} using a rational exponent x^{a/b}. What is the exponent?", data: { answerLabel: "Exponent =", correctAnswer: "frac{3}{4}" } },
    { type: "equation_numeric", stem: "Rewrite sqrt[5]{x^{2}} using a rational exponent x^{a/b}. What is the exponent?", data: { answerLabel: "Exponent =", correctAnswer: "frac{2}{5}" } },
    { type: "equation_numeric", stem: "Rewrite sqrt[3]{x^{2}} using a rational exponent x^{a/b}. What is the exponent?", data: { answerLabel: "Exponent =", correctAnswer: "frac{2}{3}" } },
    { type: "multiple_choice", stem: "Which expression is equivalent to sqrt{x^{3}}?", data: { options: [{id:"A",text:"x^{frac{3}{2}}"},{id:"B",text:"x^{frac{2}{3}}"},{id:"C",text:"x^{6}"},{id:"D",text:"3x^{frac{1}{2}}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which expression is equivalent to sqrt[3]{x^{5}}?", data: { options: [{id:"A",text:"x^{frac{5}{3}}"},{id:"B",text:"x^{frac{3}{5}}"},{id:"C",text:"x^{15}"},{id:"D",text:"5x^{frac{1}{3}}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which expression is equivalent to sqrt[4]{x}?", data: { options: [{id:"A",text:"x^{frac{1}{4}}"},{id:"B",text:"x^{4}"},{id:"C",text:"4x"},{id:"D",text:"x^{frac{4}{1}}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which expression is equivalent to sqrt[5]{x^{3}}?", data: { options: [{id:"A",text:"x^{frac{3}{5}}"},{id:"B",text:"x^{frac{5}{3}}"},{id:"C",text:"x^{15}"},{id:"D",text:"3x^{frac{1}{5}}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which expression is equivalent to sqrt{x^{7}}?", data: { options: [{id:"A",text:"x^{frac{7}{2}}"},{id:"B",text:"x^{frac{2}{7}}"},{id:"C",text:"x^{14}"},{id:"D",text:"7x^{frac{1}{2}}"}], correctId: "A" } },
    { type: "multi_select", stem: "Which expressions are equivalent to sqrt[3]{x^{2}}? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{2}{3}}"},{id:"B",text:"(sqrt[3]{x})^{2}"},{id:"C",text:"x^{frac{3}{2}}"},{id:"D",text:"2x^{frac{1}{3}}"}], correctIds: ["A","B"] } },
    { type: "multi_select", stem: "Which expressions are equivalent to sqrt[4]{x^{3}}? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{3}{4}}"},{id:"B",text:"(sqrt[4]{x})^{3}"},{id:"C",text:"x^{frac{4}{3}}"},{id:"D",text:"3x^{frac{1}{4}}"}], correctIds: ["A","B"] } },
    { type: "multi_select", stem: "Which expressions are equivalent to sqrt{x^{5}}? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{5}{2}}"},{id:"B",text:"(sqrt{x})^{5}"},{id:"C",text:"x^{frac{2}{5}}"},{id:"D",text:"5x^{frac{1}{2}}"}], correctIds: ["A","B"] } },
    { type: "multi_select", stem: "Which expressions are equivalent to sqrt[5]{x^{4}}? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{4}{5}}"},{id:"B",text:"(sqrt[5]{x})^{4}"},{id:"C",text:"x^{frac{5}{4}}"},{id:"D",text:"4x^{frac{1}{5}}"}], correctIds: ["A","B"] } },
    { type: "multi_select", stem: "Which expressions are equivalent to sqrt[3]{x^{7}}? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{7}{3}}"},{id:"B",text:"(sqrt[3]{x})^{7}"},{id:"C",text:"x^{frac{3}{7}}"},{id:"D",text:"7x^{frac{1}{3}}"}], correctIds: ["A","B"] } },
    { type: "matching_tables", stem: "Match each radical expression to its equivalent rational exponent form.", data: { rows: ["sqrt{x}","sqrt[3]{x}","sqrt[4]{x}"], columns: ["x^{frac{1}{2}}","x^{frac{1}{3}}","x^{frac{1}{4}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each radical expression to its equivalent rational exponent form.", data: { rows: ["sqrt[3]{x^{2}}","sqrt[4]{x^{3}}","sqrt{x^{5}}"], columns: ["x^{frac{2}{3}}","x^{frac{3}{4}}","x^{frac{5}{2}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each radical expression to its equivalent rational exponent form.", data: { rows: ["sqrt[5]{x}","sqrt[5]{x^{2}}","sqrt[5]{x^{3}}"], columns: ["x^{frac{1}{5}}","x^{frac{2}{5}}","x^{frac{3}{5}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each radical expression to its equivalent rational exponent form.", data: { rows: ["sqrt[3]{x^{4}}","sqrt{x^{3}}","sqrt[4]{x}"], columns: ["x^{frac{4}{3}}","x^{frac{3}{2}}","x^{frac{1}{4}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each radical expression to its equivalent rational exponent form.", data: { rows: ["sqrt[6]{x}","sqrt[6]{x^{5}}","sqrt[3]{x^{5}}"], columns: ["x^{frac{1}{6}}","x^{frac{5}{6}}","x^{frac{5}{3}}"], correct: [0,1,2] } },
  ],

  "2": [
    { type: "equation_numeric", stem: "Rewrite x^{frac{1}{2}} using radical notation.", data: { answerLabel: "Radical form =", correctAnswer: "sqrt{x}" } },
    { type: "equation_numeric", stem: "Rewrite x^{frac{1}{3}} using radical notation.", data: { answerLabel: "Radical form =", correctAnswer: "sqrt[3]{x}" } },
    { type: "equation_numeric", stem: "Rewrite x^{frac{2}{3}} using radical notation.", data: { answerLabel: "Radical form =", correctAnswer: "sqrt[3]{x^{2}}" } },
    { type: "equation_numeric", stem: "Rewrite x^{frac{3}{4}} using radical notation.", data: { answerLabel: "Radical form =", correctAnswer: "sqrt[4]{x^{3}}" } },
    { type: "equation_numeric", stem: "Rewrite x^{frac{2}{5}} using radical notation.", data: { answerLabel: "Radical form =", correctAnswer: "sqrt[5]{x^{2}}" } },
    { type: "multiple_choice", stem: "Which radical expression is equivalent to x^{frac{3}{2}}?", data: { options: [{id:"A",text:"sqrt{x^{3}}"},{id:"B",text:"sqrt[3]{x^{2}}"},{id:"C",text:"3sqrt{x}"},{id:"D",text:"sqrt{3x}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which radical expression is equivalent to x^{frac{5}{3}}?", data: { options: [{id:"A",text:"sqrt[3]{x^{5}}"},{id:"B",text:"sqrt[5]{x^{3}}"},{id:"C",text:"5sqrt[3]{x}"},{id:"D",text:"sqrt[3]{5x}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which radical expression is equivalent to x^{frac{1}{4}}?", data: { options: [{id:"A",text:"sqrt[4]{x}"},{id:"B",text:"sqrt{x^{4}}"},{id:"C",text:"4sqrt{x}"},{id:"D",text:"sqrt[4]{4x}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which radical expression is equivalent to x^{frac{4}{5}}?", data: { options: [{id:"A",text:"sqrt[5]{x^{4}}"},{id:"B",text:"sqrt[4]{x^{5}}"},{id:"C",text:"4sqrt[5]{x}"},{id:"D",text:"sqrt[5]{4x}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which radical expression is equivalent to x^{frac{7}{2}}?", data: { options: [{id:"A",text:"sqrt{x^{7}}"},{id:"B",text:"sqrt[7]{x^{2}}"},{id:"C",text:"7sqrt{x}"},{id:"D",text:"sqrt{7x}"}], correctId: "A" } },
    { type: "multi_select", stem: "Which expressions are equivalent to x^{frac{2}{3}}? Select all that apply.", data: { options: [{id:"A",text:"sqrt[3]{x^{2}}"},{id:"B",text:"(sqrt[3]{x})^{2}"},{id:"C",text:"sqrt{x^{3}}"},{id:"D",text:"2sqrt[3]{x}"}], correctIds: ["A","B"] } },
    { type: "multi_select", stem: "Which expressions are equivalent to x^{frac{3}{4}}? Select all that apply.", data: { options: [{id:"A",text:"sqrt[4]{x^{3}}"},{id:"B",text:"(sqrt[4]{x})^{3}"},{id:"C",text:"sqrt[3]{x^{4}}"},{id:"D",text:"3sqrt[4]{x}"}], correctIds: ["A","B"] } },
    { type: "multi_select", stem: "Which expressions are equivalent to x^{frac{5}{2}}? Select all that apply.", data: { options: [{id:"A",text:"sqrt{x^{5}}"},{id:"B",text:"(sqrt{x})^{5}"},{id:"C",text:"sqrt[5]{x^{2}}"},{id:"D",text:"5sqrt{x}"}], correctIds: ["A","B"] } },
    { type: "multi_select", stem: "Which expressions are equivalent to x^{frac{4}{3}}? Select all that apply.", data: { options: [{id:"A",text:"sqrt[3]{x^{4}}"},{id:"B",text:"(sqrt[3]{x})^{4}"},{id:"C",text:"sqrt[4]{x^{3}}"},{id:"D",text:"4sqrt[3]{x}"}], correctIds: ["A","B"] } },
    { type: "multi_select", stem: "Which expressions are equivalent to x^{frac{1}{5}}? Select all that apply.", data: { options: [{id:"A",text:"sqrt[5]{x}"},{id:"B",text:"sqrt[5]{x^{1}}"},{id:"C",text:"sqrt{x^{5}}"},{id:"D",text:"5x"}], correctIds: ["A","B"] } },
    { type: "matching_tables", stem: "Match each rational exponent expression to its radical form.", data: { rows: ["x^{frac{1}{2}}","x^{frac{1}{3}}","x^{frac{1}{4}}"], columns: ["sqrt{x}","sqrt[3]{x}","sqrt[4]{x}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each rational exponent expression to its radical form.", data: { rows: ["x^{frac{2}{3}}","x^{frac{3}{4}}","x^{frac{5}{2}}"], columns: ["sqrt[3]{x^{2}}","sqrt[4]{x^{3}}","sqrt{x^{5}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each rational exponent expression to its radical form.", data: { rows: ["x^{frac{1}{5}}","x^{frac{2}{5}}","x^{frac{3}{5}}"], columns: ["sqrt[5]{x}","sqrt[5]{x^{2}}","sqrt[5]{x^{3}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each rational exponent expression to its radical form.", data: { rows: ["x^{frac{4}{3}}","x^{frac{3}{2}}","x^{frac{1}{4}}"], columns: ["sqrt[3]{x^{4}}","sqrt{x^{3}}","sqrt[4]{x}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each rational exponent expression to its radical form.", data: { rows: ["x^{frac{1}{6}}","x^{frac{5}{6}}","x^{frac{5}{3}}"], columns: ["sqrt[6]{x}","sqrt[6]{x^{5}}","sqrt[3]{x^{5}}"], correct: [0,1,2] } },
  ],

  "3": [
    { type: "equation_numeric", stem: "Simplify: x^{frac{1}{2}} \u00d7 x^{frac{1}{3}}. Give the exponent in the simplified form x^{a/b}.", data: { answerLabel: "Exponent =", correctAnswer: "frac{5}{6}" } },
    { type: "equation_numeric", stem: "Simplify: x^{frac{2}{3}} \u00d7 x^{frac{1}{3}}. Give the exponent in the simplified form x^{a/b}.", data: { answerLabel: "Exponent =", correctAnswer: "1" } },
    { type: "equation_numeric", stem: "Simplify: frac{x^{frac{3}{4}}}{x^{frac{1}{4}}}. Give the exponent in the simplified form x^{a/b}.", data: { answerLabel: "Exponent =", correctAnswer: "frac{1}{2}" } },
    { type: "equation_numeric", stem: "Simplify: (x^{frac{1}{2}})^{4}. Give the exponent in the simplified form x^{a/b}.", data: { answerLabel: "Exponent =", correctAnswer: "2" } },
    { type: "equation_numeric", stem: "Simplify: frac{x^{frac{5}{6}}}{x^{frac{1}{6}}}. Give the exponent in the simplified form x^{a/b}.", data: { answerLabel: "Exponent =", correctAnswer: "frac{2}{3}" } },
    { type: "multiple_choice", stem: "Simplify: x^{frac{1}{4}} \u00d7 x^{frac{1}{4}}", data: { options: [{id:"A",text:"x^{frac{1}{2}}"},{id:"B",text:"x^{frac{1}{16}}"},{id:"C",text:"x^{frac{1}{8}}"},{id:"D",text:"x^{0}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Simplify: (x^{frac{2}{3}})^{3}", data: { options: [{id:"A",text:"x^{2}"},{id:"B",text:"x^{6}"},{id:"C",text:"x^{frac{2}{9}}"},{id:"D",text:"x^{frac{5}{3}}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Simplify: frac{x^{frac{2}{3}}}{x^{frac{1}{6}}}", data: { options: [{id:"A",text:"x^{frac{1}{2}}"},{id:"B",text:"x^{frac{1}{4}}"},{id:"C",text:"x^{frac{5}{6}}"},{id:"D",text:"x^{frac{1}{9}}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Simplify: x^{frac{3}{4}} \u00d7 x^{frac{1}{4}}", data: { options: [{id:"A",text:"x"},{id:"B",text:"x^{frac{3}{16}}"},{id:"C",text:"x^{frac{1}{2}}"},{id:"D",text:"x^{2}"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Simplify: (x^{frac{1}{3}})^{6}", data: { options: [{id:"A",text:"x^{2}"},{id:"B",text:"x^{18}"},{id:"C",text:"x^{frac{1}{18}}"},{id:"D",text:"x^{7}"}], correctId: "A" } },
    { type: "multi_select", stem: "Which of the following correctly apply the properties of exponents? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{1}{2}} \u00d7 x^{frac{1}{2}} = x"},{id:"B",text:"(x^{frac{1}{3}})^{3} = x"},{id:"C",text:"x^{frac{1}{2}} \u00d7 x^{frac{1}{2}} = x^{frac{1}{4}}"},{id:"D",text:"frac{x^{frac{3}{4}}}{x^{frac{1}{4}}} = x^{frac{1}{2}}"}], correctIds: ["A","B","D"] } },
    { type: "multi_select", stem: "Which of the following correctly apply the properties of exponents? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{2}{5}} \u00d7 x^{frac{3}{5}} = x"},{id:"B",text:"(x^{frac{2}{3}})^{3} = x^{2}"},{id:"C",text:"(x^{frac{2}{3}})^{3} = x^{6}"},{id:"D",text:"frac{x^{frac{5}{6}}}{x^{frac{1}{3}}} = x^{frac{1}{2}}"}], correctIds: ["A","B","D"] } },
    { type: "multi_select", stem: "Which of the following correctly apply the properties of exponents? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{1}{4}} \u00d7 x^{frac{1}{4}} = x^{frac{1}{2}}"},{id:"B",text:"(x^{frac{1}{2}})^{2} = x"},{id:"C",text:"x^{frac{1}{4}} \u00d7 x^{frac{1}{4}} = x^{frac{1}{16}}"},{id:"D",text:"frac{x^{frac{2}{3}}}{x^{frac{1}{3}}} = x^{frac{1}{3}}"}], correctIds: ["A","B","D"] } },
    { type: "multi_select", stem: "Which of the following correctly apply the properties of exponents? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{3}{5}} \u00d7 x^{frac{2}{5}} = x"},{id:"B",text:"(x^{frac{1}{5}})^{5} = x"},{id:"C",text:"x^{frac{3}{5}} \u00d7 x^{frac{2}{5}} = x^{frac{6}{25}}"},{id:"D",text:"frac{x^{frac{4}{5}}}{x^{frac{1}{5}}} = x^{frac{3}{5}}"}], correctIds: ["A","B","D"] } },
    { type: "multi_select", stem: "Which of the following correctly apply the properties of exponents? Select all that apply.", data: { options: [{id:"A",text:"x^{frac{1}{6}} \u00d7 x^{frac{1}{3}} = x^{frac{1}{2}}"},{id:"B",text:"(x^{frac{1}{4}})^{4} = x"},{id:"C",text:"x^{frac{1}{6}} \u00d7 x^{frac{1}{3}} = x^{frac{1}{18}}"},{id:"D",text:"frac{x^{frac{5}{6}}}{x^{frac{1}{2}}} = x^{frac{1}{3}}"}], correctIds: ["A","B","D"] } },
    { type: "matching_tables", stem: "Match each expression to its simplified form.", data: { rows: ["x^{frac{1}{2}} \u00d7 x^{frac{1}{2}}","x^{frac{1}{2}} \u00d7 x^{frac{1}{3}}","frac{x^{frac{3}{4}}}{x^{frac{1}{4}}}"], columns: ["x","x^{frac{5}{6}}","x^{frac{1}{2}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its simplified form.", data: { rows: ["(x^{frac{1}{2}})^{2}","(x^{frac{1}{2}})^{4}","(x^{frac{1}{3}})^{9}"], columns: ["x","x^{2}","x^{3}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its simplified form.", data: { rows: ["x^{frac{2}{3}} \u00d7 x^{frac{1}{3}}","frac{x^{frac{5}{6}}}{x^{frac{1}{6}}}","x^{frac{1}{4}} \u00d7 x^{frac{1}{4}}"], columns: ["x","x^{frac{2}{3}}","x^{frac{1}{2}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its simplified form.", data: { rows: ["x^{frac{3}{5}} \u00d7 x^{frac{2}{5}}","frac{x^{frac{4}{5}}}{x^{frac{1}{5}}}","x^{frac{1}{6}} \u00d7 x^{frac{1}{3}}"], columns: ["x","x^{frac{3}{5}}","x^{frac{1}{2}}"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its simplified form.", data: { rows: ["(x^{frac{1}{6}})^{3}","(x^{frac{1}{4}})^{2}","(x^{frac{1}{2}})^{2}"], columns: ["x^{frac{1}{2}}","x^{frac{1}{2}}","x"], correct: [0,0,2] } },
  ],

  "4": [
    { type: "equation_numeric", stem: "Solve: x^{frac{1}{2}} = 5", data: { answerLabel: "x =", correctAnswer: "25" } },
    { type: "equation_numeric", stem: "Solve: x^{frac{1}{3}} = 4", data: { answerLabel: "x =", correctAnswer: "64" } },
    { type: "equation_numeric", stem: "Solve: x^{frac{2}{3}} = 4", data: { answerLabel: "x =", correctAnswer: "8" } },
    { type: "equation_numeric", stem: "Solve: sqrt{x} = 9", data: { answerLabel: "x =", correctAnswer: "81" } },
    { type: "equation_numeric", stem: "Solve: x^{frac{3}{2}} = 8", data: { answerLabel: "x =", correctAnswer: "4" } },
    { type: "multiple_choice", stem: "Solve: x^{frac{1}{4}} = 2", data: { options: [{id:"A",text:"16"},{id:"B",text:"8"},{id:"C",text:"2"},{id:"D",text:"0.5"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve: x^{frac{1}{2}} = 6", data: { options: [{id:"A",text:"36"},{id:"B",text:"12"},{id:"C",text:"3"},{id:"D",text:"6"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve: x^{frac{2}{5}} = 4", data: { options: [{id:"A",text:"32"},{id:"B",text:"8"},{id:"C",text:"16"},{id:"D",text:"1.6"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve: sqrt[3]{x} = 5", data: { options: [{id:"A",text:"125"},{id:"B",text:"15"},{id:"C",text:"25"},{id:"D",text:"5"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Solve: x^{frac{3}{4}} = 8", data: { options: [{id:"A",text:"16"},{id:"B",text:"6"},{id:"C",text:"24"},{id:"D",text:"64"}], correctId: "A" } },
    { type: "multi_select", stem: "Which steps correctly solve x^{frac{2}{3}} = 9? Select all that apply.", data: { options: [{id:"A",text:"Raise both sides to the power frac{3}{2}"},{id:"B",text:"x = 9^{frac{3}{2}}"},{id:"C",text:"x = 27"},{id:"D",text:"x = 6"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which steps correctly solve x^{frac{1}{2}} = 7? Select all that apply.", data: { options: [{id:"A",text:"Square both sides"},{id:"B",text:"x = 7^{2}"},{id:"C",text:"x = 49"},{id:"D",text:"x = 14"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which steps correctly solve x^{frac{3}{2}} = 27? Select all that apply.", data: { options: [{id:"A",text:"Raise both sides to the power frac{2}{3}"},{id:"B",text:"x = 27^{frac{2}{3}}"},{id:"C",text:"x = 9"},{id:"D",text:"x = 18"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which steps correctly solve sqrt[3]{x} = 2? Select all that apply.", data: { options: [{id:"A",text:"Cube both sides"},{id:"B",text:"x = 2^{3}"},{id:"C",text:"x = 8"},{id:"D",text:"x = 6"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which steps correctly solve x^{frac{2}{5}} = 4? Select all that apply.", data: { options: [{id:"A",text:"Raise both sides to the power frac{5}{2}"},{id:"B",text:"x = 4^{frac{5}{2}}"},{id:"C",text:"x = 32"},{id:"D",text:"x = 10"}], correctIds: ["A","B","C"] } },
    { type: "matching_tables", stem: "Match each equation to its solution.", data: { rows: ["x^{frac{1}{2}} = 4","x^{frac{1}{3}} = 3","sqrt{x} = 10"], columns: ["16","27","100"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to its solution.", data: { rows: ["x^{frac{2}{3}} = 9","x^{frac{3}{2}} = 27","x^{frac{1}{4}} = 3"], columns: ["27","9","81"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to its solution.", data: { rows: ["sqrt[3]{x} = 4","x^{frac{2}{5}} = 4","x^{frac{1}{2}} = 12"], columns: ["64","32","144"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to its solution.", data: { rows: ["x^{frac{3}{4}} = 8","x^{frac{1}{5}} = 2","sqrt{x} = 15"], columns: ["16","32","225"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each equation to its solution.", data: { rows: ["x^{frac{1}{2}} = 8","x^{frac{2}{3}} = 25","sqrt[3]{x} = 6"], columns: ["64","125","216"], correct: [0,1,2] } },
  ],

  "5": [
    { type: "equation_numeric", stem: "Evaluate: 8^{frac{2}{3}}", data: { answerLabel: "Value =", correctAnswer: "4" } },
    { type: "equation_numeric", stem: "Evaluate: 16^{frac{3}{4}}", data: { answerLabel: "Value =", correctAnswer: "8" } },
    { type: "equation_numeric", stem: "Evaluate: 27^{frac{2}{3}}", data: { answerLabel: "Value =", correctAnswer: "9" } },
    { type: "equation_numeric", stem: "Evaluate: 32^{frac{2}{5}}", data: { answerLabel: "Value =", correctAnswer: "4" } },
    { type: "equation_numeric", stem: "Evaluate: 4^{frac{5}{2}}", data: { answerLabel: "Value =", correctAnswer: "32" } },
    { type: "multiple_choice", stem: "Evaluate: 9^{frac{3}{2}}", data: { options: [{id:"A",text:"27"},{id:"B",text:"13.5"},{id:"C",text:"729"},{id:"D",text:"81"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Evaluate: 25^{frac{3}{2}}", data: { options: [{id:"A",text:"125"},{id:"B",text:"37.5"},{id:"C",text:"625"},{id:"D",text:"75"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Evaluate: 64^{frac{2}{3}}", data: { options: [{id:"A",text:"16"},{id:"B",text:"42.67"},{id:"C",text:"4096"},{id:"D",text:"128"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Evaluate: 81^{frac{3}{4}}", data: { options: [{id:"A",text:"27"},{id:"B",text:"60.75"},{id:"C",text:"6561"},{id:"D",text:"243"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Evaluate: 100^{frac{3}{2}}", data: { options: [{id:"A",text:"1000"},{id:"B",text:"150"},{id:"C",text:"10000"},{id:"D",text:"300"}], correctId: "A" } },
    { type: "multi_select", stem: "Which of the following equal 8? Select all that apply.", data: { options: [{id:"A",text:"4^{frac{3}{2}}"},{id:"B",text:"64^{frac{1}{2}}"},{id:"C",text:"16^{frac{2}{3}}"},{id:"D",text:"2^{3}"}], correctIds: ["A","B","D"] } },
    { type: "multi_select", stem: "Which of the following equal 9? Select all that apply.", data: { options: [{id:"A",text:"27^{frac{2}{3}}"},{id:"B",text:"81^{frac{1}{2}}"},{id:"C",text:"3^{2}"},{id:"D",text:"9^{frac{3}{2}}"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which of the following equal 4? Select all that apply.", data: { options: [{id:"A",text:"8^{frac{2}{3}}"},{id:"B",text:"32^{frac{2}{5}}"},{id:"C",text:"16^{frac{1}{2}}"},{id:"D",text:"64^{frac{2}{3}}"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which of the following equal 16? Select all that apply.", data: { options: [{id:"A",text:"64^{frac{2}{3}}"},{id:"B",text:"8^{frac{4}{3}}"},{id:"C",text:"4^{2}"},{id:"D",text:"32^{frac{2}{5}}"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which of the following equal 32? Select all that apply.", data: { options: [{id:"A",text:"4^{frac{5}{2}}"},{id:"B",text:"2^{5}"},{id:"C",text:"8^{frac{5}{3}}"},{id:"D",text:"16^{frac{3}{4}}"}], correctIds: ["A","B","C"] } },
    { type: "matching_tables", stem: "Match each expression to its exact value.", data: { rows: ["8^{frac{2}{3}}","16^{frac{3}{4}}","27^{frac{2}{3}}"], columns: ["4","8","9"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its exact value.", data: { rows: ["9^{frac{3}{2}}","25^{frac{3}{2}}","4^{frac{5}{2}}"], columns: ["27","125","32"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its exact value.", data: { rows: ["32^{frac{2}{5}}","64^{frac{2}{3}}","81^{frac{3}{4}}"], columns: ["4","16","27"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its exact value.", data: { rows: ["100^{frac{3}{2}}","36^{frac{3}{2}}","49^{frac{3}{2}}"], columns: ["1000","216","343"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to its exact value.", data: { rows: ["8^{frac{4}{3}}","27^{frac{4}{3}}","16^{frac{5}{4}}"], columns: ["16","81","32"], correct: [0,1,2] } },
  ],

  "6": [
    { type: "equation_numeric", stem: "Compare 8^{frac{1}{3}} and 3. Which is greater? Answer with the value of 8^{frac{1}{3}}.", data: { answerLabel: "8^{frac{1}{3}} =", correctAnswer: "2" } },
    { type: "equation_numeric", stem: "Compare 9^{frac{1}{2}} and 3.5. Answer with the value of 9^{frac{1}{2}}.", data: { answerLabel: "9^{frac{1}{2}} =", correctAnswer: "3" } },
    { type: "equation_numeric", stem: "Compare 16^{frac{1}{4}} and 2.5. Answer with the value of 16^{frac{1}{4}}.", data: { answerLabel: "16^{frac{1}{4}} =", correctAnswer: "2" } },
    { type: "equation_numeric", stem: "Compare 27^{frac{1}{3}} and 3. Answer with the value of 27^{frac{1}{3}}.", data: { answerLabel: "27^{frac{1}{3}} =", correctAnswer: "3" } },
    { type: "equation_numeric", stem: "Compare 4^{frac{3}{2}} and 9. Answer with the value of 4^{frac{3}{2}}.", data: { answerLabel: "4^{frac{3}{2}} =", correctAnswer: "8" } },
    { type: "multiple_choice", stem: "Which is greater, 8^{frac{1}{3}} or 3?", data: { options: [{id:"A",text:"3 is greater"},{id:"B",text:"8^{frac{1}{3}} is greater"},{id:"C",text:"They are equal"},{id:"D",text:"Cannot be determined"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which is greater, 16^{frac{1}{4}} or 2.5?", data: { options: [{id:"A",text:"2.5 is greater"},{id:"B",text:"16^{frac{1}{4}} is greater"},{id:"C",text:"They are equal"},{id:"D",text:"Cannot be determined"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which is greater, 27^{frac{1}{3}} or 3?", data: { options: [{id:"A",text:"They are equal"},{id:"B",text:"27^{frac{1}{3}} is greater"},{id:"C",text:"3 is greater"},{id:"D",text:"Cannot be determined"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which is greater, 4^{frac{3}{2}} or 9?", data: { options: [{id:"A",text:"9 is greater"},{id:"B",text:"4^{frac{3}{2}} is greater"},{id:"C",text:"They are equal"},{id:"D",text:"Cannot be determined"}], correctId: "A" } },
    { type: "multiple_choice", stem: "Which is greater, 9^{frac{1}{2}} or 3.5?", data: { options: [{id:"A",text:"3.5 is greater"},{id:"B",text:"9^{frac{1}{2}} is greater"},{id:"C",text:"They are equal"},{id:"D",text:"Cannot be determined"}], correctId: "A" } },
    { type: "multi_select", stem: "Which of the following comparisons are true? Select all that apply.", data: { options: [{id:"A",text:"8^{frac{1}{3}} < 3"},{id:"B",text:"9^{frac{1}{2}} = 3"},{id:"C",text:"16^{frac{1}{4}} = 2"},{id:"D",text:"27^{frac{1}{3}} < 3"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which of the following comparisons are true? Select all that apply.", data: { options: [{id:"A",text:"4^{frac{3}{2}} < 9"},{id:"B",text:"25^{frac{1}{2}} = 5"},{id:"C",text:"32^{frac{1}{5}} = 2"},{id:"D",text:"4^{frac{3}{2}} > 9"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which of the following comparisons are true? Select all that apply.", data: { options: [{id:"A",text:"64^{frac{1}{3}} = 4"},{id:"B",text:"49^{frac{1}{2}} < 8"},{id:"C",text:"100^{frac{1}{2}} = 10"},{id:"D",text:"64^{frac{1}{3}} = 8"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which of the following comparisons are true? Select all that apply.", data: { options: [{id:"A",text:"81^{frac{1}{4}} = 3"},{id:"B",text:"81^{frac{1}{2}} = 9"},{id:"C",text:"81^{frac{1}{4}} < 81^{frac{1}{2}}"},{id:"D",text:"81^{frac{1}{4}} > 81^{frac{1}{2}}"}], correctIds: ["A","B","C"] } },
    { type: "multi_select", stem: "Which of the following comparisons are true? Select all that apply.", data: { options: [{id:"A",text:"2^{frac{1}{2}} < 2"},{id:"B",text:"2^{2} > 2"},{id:"C",text:"2^{1} = 2"},{id:"D",text:"2^{frac{1}{2}} > 2"}], correctIds: ["A","B","C"] } },
    { type: "matching_tables", stem: "Match each comparison to whether it is true.", data: { rows: ["8^{frac{1}{3}} ___ 3","27^{frac{1}{3}} ___ 3","16^{frac{1}{4}} ___ 2.5"], columns: ["<","=",">"], correct: [0,1,0] } },
    { type: "matching_tables", stem: "Match each expression to whether it is less than, equal to, or greater than 10.", data: { rows: ["100^{frac{1}{2}}","4^{frac{5}{2}}","4^{frac{3}{2}}"], columns: ["equal to 10","greater than 10","less than 10"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to whether it is less than, equal to, or greater than 5.", data: { rows: ["25^{frac{1}{2}}","8^{frac{1}{3}}","4^{frac{3}{2}}"], columns: ["equal to 5","less than 5","greater than 5"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to whether it is less than, equal to, or greater than 4.", data: { rows: ["16^{frac{1}{2}}","25^{frac{1}{2}}","8^{frac{1}{3}}"], columns: ["equal to 4","greater than 4","less than 4"], correct: [0,1,2] } },
    { type: "matching_tables", stem: "Match each expression to whether it is less than, equal to, or greater than 6.", data: { rows: ["36^{frac{1}{2}}","27^{frac{2}{3}}","8^{frac{1}{3}}"], columns: ["equal to 6","greater than 6","less than 6"], correct: [0,1,2] } },
  ],
};
